name: Sync Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git remote add upstream https://github.com/magemonkeystudio/genesis.git
          git fetch upstream --prune
          git checkout dev || git checkout -b dev origin/dev
          git reset --hard upstream/dev
          git checkout upstream/dev -- .
          git restore --source=HEAD --staged --worktree .github/workflows || true
          git add -A
          git commit -m "S
